### ISSUE TITLE
Runtime error using nuxct 0.6.0

### ISSUE THREAD

**Issue by marcowenwolf** [nuagenetworks/nuxctl#20]
Using version 0.6.0 causes runtime error. Is nuxctl still supported?

```
marcwolf@laptop:~/Documents/NuageX> nuxctl version
0.6.0
marcwolf@laptop:~/Documents/NuageX> nuxctl list-labs
Loading user credentials from 'user_creds.yml' file...
Logging 'marcwolf' user in...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x70ef4a]

goroutine 1 [running]:
github.com/nuagenetworks/nuxctl/nuagex.(*User).Login(0xb7bae0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/nuagenetworks/nuxctl/nuagex/user.go:72 +0x32a
github.com/nuagenetworks/nuxctl/cmd.loginUser(0xb76380, 0xb985b0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/nuagenetworks/nuxctl/cmd/loginUser.go:14 +0x59
github.com/nuagenetworks/nuxctl/cmd.listLabs(0xb76380, 0xb985b0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/nuagenetworks/nuxctl/cmd/listLabs.go:29 +0x5c
github.com/spf13/cobra.(*Command).execute(0xb76380, 0xb985b0, 0x0, 0x0, 0xb76380, 0xb985b0)
        /home/travis/gopath/src/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xb76840, 0x9, 0xc0000ddf48, 0x1)
        /home/travis/gopath/src/github.com/spf13/cobra/command.go:852 +0x2c0
github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/src/github.com/spf13/cobra/command.go:800
github.com/nuagenetworks/nuxctl/cmd.Execute(0x839f2c, 0x5)
        /home/travis/gopath/src/github.com/nuagenetworks/nuxctl/cmd/root.go:35 +0xdd
main.main()
        /home/travis/gopath/src/github.com/nuagenetworks/nuxctl/main.go:9 +0x36

marcwolf@laptop:~/Documents/NuageX> cat user_creds.yml 
---
username: "<user>"
password: "<password>"

```

**Comment by hellt** [comment]
Hi,
I think this is happening because TLS certificate for nuagex has expired.
Since I heard that nuagex might be discontinued, I do not plan to maintain
nuxctl.
But if anyone will come up with a PR, I will merge it
